kevinconway/rpmvenv

- rpmvenv/cmd.py
- setup.py
Previously this was accomplished by allowing the exceptions to
bubble up. Now that we catch the exception we need to exit with
a non-zero code.
Signed-off-by: Kevin Conway <kevinjacobconway@gmail.com>
> Add failure exit code on RPM build failure

- README.rst
- rpmvenv/cmd.py
- rpmvenv/render.py
- rpmvenv/rpmbuild.py
- rpmvenv/templates/rpm.spec
- setup.py
- tests/conftest.py
- tests/test_cmd.py
This name is distinct from the installation directory name and a
new option is added to handle the distinction.
Tests are updated to account for the change.
Signed-off-by: Kevin Conway <kevinjacobconway@gmail.com>
> Add support for custom RPM package names

- rpmvenv/extensions/python/venv.py
- setup.py
Pip is unable to function as a standalone script when the shebang
header exceeds the maximum character length. Call the venv python
to execute pip resolves this issue.
Signed-off-by: Kevin Conway <kevinjacobconway@gmail.com>
> Fix bug related to deeply nested virtualenv

- README.rst
Hi,
Could be seen as an issue: Took me a while to figure out that *confpy* requires a dict and therefore you'd probably expect the 'enabled' key in "extensions": {"enabled" .. in the config.json file.
BTW, thanks for this very helpful tool!
> Fixing a missing key in the example config.json and adding a comment that 'rpmbuild' is required.

- rpmvenv/extensions/python/venv.py
`cd` and `cd -` are [POSIX](http://pubs.opengroup.org/stage7tc1/utilities/cd.html) and should fulfil the same purpose here.
I encountered an `/bin/sh: pushd: not found` error on a vanilla ubuntu.
An alternative could be to change the `#!/bin/sh` on top of the generated file to `#!/bin/bash`.
> replace pushd and popd with cd

- rpmvenv/cli.py
- setup.py
If the --source option is not an absolute path it breaks the copy
call used to move the source into the build directory. This patch
adds a call to normalize the path with abspath.
Signed-off-by: Kevin Conway <kevinjacobconway@gmail.com>
> Fix issue with passing relative paths as source

- rpmvenv/extensions/core.py
Release can be more than an integer, for example if you want to follow the good practice of automatically adding the distribution (i.e.: el5, el6, el7) using %{?dist}.
> Release shouldn't be limited to integers only.

- README.rst
- rpmvenv/extensions/files/extras.py
- rpmvenv/extensions/files/option.py
- tests/conftest.py
- tests/test_fileoption.py
Support for more advanced files (e.g. docs and config) is provided
via the "file_extras" plugin.
For simple file copies and backwards compatibility, colon-delimited
values are still supported.
Additionally, a `dict` format is supported. The required keys are
`src` and `dest` which behave the same as in the legacy syntax. To
mark a file as a configuration file, the `config` key should be `True`.
The same applies for documentation files (with the key `doc`).
If the value for the `config` key is a string, this will be used to
further customize the directive. This is typically used with
`noreplace` or `missingok`, which will produce `%config(noreplace)` and
`%config(missingok)` respectively.
Example configuration (JSON):
```json
{
"file_extras": {
"files": [
"bar:opt/foo/bar",
{
"src": …
```
> Allow customization of additional files

- test-requirements.txt
Any version beyond `4.2.15` is made to be incompatible with py26. This patch pins the project to `4.2.15` as we want to preserve py26 compatibility and support for now.
> Pin isort (pytest dep) to a py26 compat version

- README.rst
- rpmvenv/extensions/core.py
This exposes the RPM SPEC file fields `Obsoletes` and `Conflicts` into the core extension of the rpmvenv configuration file.
> Add obsoletes and conflicts core config options

- rpmvenv/extensions/python/venv.py
In current version of `rpmvenv` installing packages from relative paths in `requirements.txt` is broken.
There are times when you need to build a project that has a git submodule which located inside project source directory. A natural way to do this is write that dependency in requirements.txt in form:
```
submodule/
```
According to [requirements file format](https://pip.pypa.io/en/stable/reference/pip_install/#requirements-file-format) it is a common thing.
But in current version of `rpmvenv` generated spec will be as follow: 
```
%install
%{venv_cmd} %{venv_dir}
%{venv_pip} -r %{SOURCE0}/requirements.txt
cd %{SOURCE0}
%{venv_python} setup.py install
```
And installing of `submodule` will be failed because current directory will not contain `submodule/` folder at that moment.
```
+ …
```
> Fix installing packages from relative paths in requirements.txt

- .travis.yml
- test-requirements.txt
- Add 3.5, 3.6 and 3.7 (which requires xenial)
- Don't install pyflakes on 2.6 or 3.3
- Only install pylint on >= 2.7
- Add -v to pytest to see which fixtures are being used
> Travis build fixes

- README.rst
- rpmvenv/extensions/python/venv.py
- tests/conftest.py
- tests/test_venv.py
This installs the application with `pip install .` rather than `python setup.py install` (which installs the application as an egg).
> Add use_pip_install option for venv. 

- .travis.yml
- README.rst
- test-requirements.txt
- tests/test_cli.py
- tox.ini
Add new Python versions for tox.
Change pep8 to pycodestyle to account for the pep8 name deprecation.
Add manylinux test suite to travis now that the problem is patched.
> Update travis, tox, and README files

- .travis.yml
- README.rst
- rpmvenv/extensions/python/venv.py
- tests/conftest.py
- tests/test_venv.py
It's possible to reduce size of resulting rpm package if remove compiled bytecode.
> Remove pycache from venv

- setup.py
The semver library stopped working for legacy Python versions after the
2.9.1 release. This adds a less than 2.10 restriction to the abstract
dependency requirements so that folks don't need to all add a pin to
their requirements.txt.
> Add semver version limit due to compat changes

- rpmvenv/extensions/python/venv.py
Fix issue with strip
The following is a proposed solution for fixing the following issue. 
While having the requirement of "opencv-python-headless", using the settings "strip_binaries": false
and QA_SKIP_BUILD_ROOT=1 and running "from cv2 import *" in the rpmvenv created venv you get the exception:
```text
Traceback (most recent call last):
File "test.py", line 1, in <module>
from cv2 import * 
File "//opt/issue/issue/lib64/python3.6/site-packages/cv2/__init__.py", line 5, in <module>
from .cv2 import *
ImportError: //opt/issue/issue/lib64/python3.6/site-packages/cv2/cv2.cpython-36m-x86_64-linux-gnu.so: ELF load command address/offset not properly aligned
```
Using "strip_binaries": false and QA_SKIP_BUILD_ROOT=1 should not strip any binaries.
While investigating the issue, it was found, …
> Fix issue with strip

- .github/workflows/ci.yml
- requirements.txt
- tests/conftest.py
This removes the workaround in the tests that was used to skip nu shell
installation in the virtualenv and updates tests to use the latest
venvctrl version.
The latest version of venvctrl also delcares a dependency on virtualenv
so it no longer needs to be manually installed in the CI configuration.
> Update venvctrl for nu shell support

- setup.py
This release drops support for all Python versions that have reached end
of life status.
> Initial v2 release

- .github/workflows/ci.yml
- .travis.yml
- rpmvenv/extensions/files/extras.py
- rpmvenv/extensions/files/option.py
- tests/test_fileoption.py
instead of relying on chmod/chown for files use the %attr directive of rpm. Particularly useful for files_extras
Needed this for a project of mine, so I might as well give back to the community.
> add support for rpm %attr for files

- README.rst
- requirements.txt
- tests/conftest.py
There's no change to rpmvenv but a recent patch to venvctrl has removed the need for nushell related workarounds. Users pulling in the 0.6.0 or later version of venvctrl will automatically have the patch applied. Users no longer need to disable nushell for rpmvenv to work. This may change again in the future if virtualenv makes more changes to activation scripts.
> Remove nushell warnings in README
